// Pseudo-random numbers = Numbers that appear random but are generated by a deterministic algorithm.
// rand() = Generates a pseudo-random integer.
// srand() = Sets the starting point (seed) for the random number generator.
// time(NULL) = Gets the current time, which provides a different seed each time the program runs.
// RAND_MAX = The maximum value that rand() can return.

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {

    // Seed the random number generator using the current time.
    // This helps produce a different sequence of numbers each time the program runs.
    srand(time(NULL));

    // Set the minimum value for our desired random-number range.   
    int min = 50;

    // Set the maximum value for our desired random-number range.
    int max = 100;

    // Generate a pseudo-random number between 50 and 100 (inclusive).
    // rand() % (max - min + 1) produces a value from 0 to 50.
    // Adding min shifts the range from 0-50 to 50-100.
    int randomNumber = (rand() % (max - min + 1)) + min;

    // Print the random number generated between 50 and 100.
    printf("%d\n", randomNumber);

    // Generate and print another pseudo-random number.
    // This can be anywhere from 0 to RAND_MAX.
    printf("%d\n", rand());


    // Print RAND_MAX, which represents the maximum value that rand() can return.
    printf("%d", RAND_MAX);

    return 0;
}